[colors]
background = #1d2021
foreground = #ebdbb2

accent     = #00ccff
muted      = #e16d76
text-dark  = #555555

[bar/mybar]
width  = 100%
height = 29
radius = 2

background = ${colors.background}
foreground = ${colors.foreground}

padding-right = 1

font-0 = "CodeNewRoman Nerd Font:size=16;2"

modules-left = xworkspaces
modules-center = date
modules-right = cpu sep memory sep pulseaudio tray

tray-position = right
tray-padding = 2
tray-scale = 1.0
tray-detached = false

;; Modules:

[module/xworkspaces]
type = internal/xworkspaces
pin-workspaces = 1 2 3 4 5 6 7 8 9
enable-click = true
enable-scroll = true
enable-urgent = true

label-active = %name%
label-active-background = ${colors.accent}
label-active-foreground = ${colors.text-dark}
label-active-padding = 1

label-occupied = %name%
label-occupied-foreground = ${colors.text-dark}
label-occupied-padding = 1

label-inactive = %name%
label-inactive-padding = 1

label-empty = %name%
label-empty-padding = 1

label-urgent = %name%


[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "  "
format-prefix-foreground = ${colors.accent}
format = <label>
label = CPU %percentage:2%%


[module/memory]
type = internal/memory
interval = 2
format-prefix = "  "
format-prefix-foreground = ${colors.accent}
format = <label>
label = RAM %percentage_used:2%%


[module/date]
type = internal/date
interval = 1
date = "%Y/%m/%d %H:%M:%S"
label = %date%
format-prefix = "󱑃 "
format-prefix-foreground = ${colors.accent}


[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = "  "
format-volume-prefix-foreground = ${colors.accent}
format-volume = <label-volume>
label-volume = VOL %percentage%%
label-muted = muted
label-muted-foreground = ${colors.muted}


[module/sep]
type = custom/text
content = " | "